# BaseAPI Global Configuration

# casbin configuration
# casbin:
#   model-path: './resource/rbac_model.conf'

# jwt configuration
jwt:
  signing-key: 'baseapiPlus'

app:
  run-mode: 'debug'
  http-port: 8000
  read-timeout: 60s
  write-timeout: 60s
  page-size: 10

# mysql connect configuration
mysql:
  username: root
  password: ''
  path: '127.0.0.1:3306'
  db-name: 'testdb'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true

# oss configuration

# redis configuration
# redis:
#   addr: '127.0.0.1:6379'
#   password: ''
#   db: 0

# system configuration
# system:
#   use-multipoint: false
#   env: 'public'  # Change to "develop" to skip authentication for development mode
#   addr: 8888
#   db-type: "mysql"  # support mysql/sqlite

# logger configuration
# log:
#   prefix: '[GIN-VUE-ADMIN]'
#   log-file: true
#   stdout: 'DEBUG'
#   file: 'DEBUG'
