info:
  contact: {}
  license: {}
paths:
  /api/v1/users:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      - description: IsActive
        in: query
        name: is_active
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增用户
swagger: "2.0"
